version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-test
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/test_db"
    depends_on:
      - db
    command: ["pytest", "--cache-clear", "--disable-warnings", "--cov=app", "--cov-report=html"]
    volumes:
      - .:/app
      - ./coverage_report:/app/htmlcov

  db:
    image: postgres:15
    container_name: test-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
